[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Gavin Mead <gavin.w.mead@gmail.com>"]
rust-version = "1.81"
readme = "README.md"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/gavinmead/sqliters"

[workspace.dependencies]
bytes = "1"